# Linked Slides Add-on - Trigger Private Repository Deployment Workflow.
# Copyright (c) 2025 Green Duck Punch, LLC. All rights reserved.
# This file is proprietary and all rights are reserved by Green Duck Punch, LLC.
# Unauthorized use, reproduction, or distribution is prohibited.

name: Trigger Private Repo Deployment

on:
  push:
    branches:
      - main # Triggers when changes are pushed to the main branch

jobs:
  dispatch_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Send workflow_dispatch to private repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_DISPATCH_TOKEN }} # PAT with workflow_dispatch scope on private repo
          repository: 'Green-Duck-Punch-LLC/private-linked-slides-addon-deploy' # Replace with your private repo path (e.g., your_org/your_private_repo_name)
          event: 'deploy-from-public-repo'
          client-payload: '{"public_repo_owner": "${{ github.repository_owner }}", "public_repo_name": "${{ github.event.repository.name }}"}'

      - name: Echo Dispatch Status
        run: echo "Successfully dispatched 'deploy-from-public-repo' event to private repository."
